name: Continuous Integration

permissions:
  contents: read #Recommended settings to ensure proper operation

on: #Event that triggers the workflow
  pull_request:
    branches: [main] #The workflow runs when a pull request is made to the main branch


jobs: #A workflow run is made up of one or more jobs, which run in parallel by default

  build:
    name: Build Project
    runs-on: ubuntu-latest #Define the type of machine to run the job on.
    steps:
    - uses: actions/checkout@v6 #Latest available version
    
    - name: Build Task
      run: mvn -B compile       #compile: Compile the source code of the project
                                  #-B: Run in non-interactive (batch) mode (disables output color)

  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Test Task
      run: mvn -B test #Test the compiled source code using a suitable unit testing framework
