name: Continuos Delivery

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Project
        uses: actions/checkout@v6

      - name: Configure Java
        uses: actions/setup-java@v5
        with:
            java-version: '17'
            distribution: 'oracle' # See 'Supported distributions' for available options

      - name: Package Project
        run: mvn -B package

      - name: Release Project
        uses: softprops/action-gh-release@v2.6.2
        with:
          files: target/*.jar

        
      

